### ISSUE TITLE
Group Milestone - Project Planning - Diglett Team

### ISSUE THREAD

**Issue by thuanmb** [thuanmb/freebie#1]
Hi,

This's the submission of our team. Please help us review. Let us know if anything we need to update/improve in our user stories.

Thanks,
Thuan
/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Ruby submission, thuanmb!

:fearful: Unfortunately **there are some problems** with your submission:
- I couldn't find a walkthrough GIF referenced from your `README.md`. Please use [RecordIt](http://recordit.co) or [LICEcap](http://www.cockos.com/licecap/) to record an animated GIF of your app in action, and include it in your `README.md`.

**Comment by chug2k** [comment]
Oops. Don't worry about the walkthrough GIF. :P

**Comment by chug2k** [comment]
I really love this idea. It's been done before in the U.S., but I think you put a new spin on it with your "campaigns" for charity. Wow, this Ruby class is much more charitable than our Swift classes. ;)

First, some feedback on your idea:
- This is called "freecycling" (free + recycling) in the us, and the original site is here: https://www.freecycle.org/. It is :hankey: . 
- The practical implementation, which people use, is a classifieds site called Craigslist, that has a "Free" section: https://sfbay.craigslist.org/search/zip. 

Now, as for the schema:
- For campaigns, should they have an "end" date? Or some sort of "done" criteria? For example, kickstarter.org has both a time limit and a money limit. 
- Is there some way to show progress on a campaign? It's really cool if you can see "collected 25 of 50 books!" or something like that. 
- If you want to support "notifications", where do you save that data? 
- How do I answer a request?

Now, for the wireframes:
- I like the idea of campaigns a lot more than random stuff. If you look at that craigslist link, it's a really ugly collection of things. So maybe you can feature the campaigns front and center on the homepage, instead of a bunch of old clothes. Old clothes are ugly, they don't do well as a front-page!
- There are a lot more screens. I know they seem easy, but wireframing them out will make you realize how many features you really have. And doing something like "messages" is pretty hard to design correctly. So **please** finish the wireframes. 

Overall, I think this is a very promising idea! 

/cc @harley

**Comment by thuanmb** [comment]
Hi @chug2k ,

Thanks for your feedback, we'll have a discussion on your feedback and update the schema as well as wireframes.

Thanks,
Thuan
